menu:
    Blog: /
    # Tags: /tags/
    Archive: /archives/
    About: /about/
    # Category: /category/
    GitHub: https://github.com/SimoneCheng
    Rss: /atom.xml
    # Friends: /friends/

favicon: favicon.png
logo: favicon.png
avatar: favicon.png
# Comment
# e.g disqus: achjqz
disqus:

gitalk:
    on: false
    clientID: 
    clientSecret: 
    owner:
    admin:
    repo:       

# Analytics
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2021