menu:
    Blog: /
    Archive: /archives/
    Category: /categories/
    GitHub: https://github.com/achjqz
    Rss: /atom.xml

favicon: favicon.png
logo: favicon.png

# Comment
# e.g disqus: achjqz
disqus:

# Analytics
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2020
