menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/achjqz
    GitHub: https://github.com/achjqz
    Rss: /atom.xml

favicon: favicon.png
logo: favicon.png

# Comment
# e.g disqus: achjqz
disqus:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2020
