menu:
    Blog: /
    Tags: /tags/
    Archive: /archives/
    About: /about/
    # Category: /category/
    # GitHub: https://github.com/SimoneCheng
    Rss: /atom.xml
    # Friends: /friends/

favicon: dovefavicon.png
logo: dovefavicon.png
avatar: favicon.png
# Comment
# e.g disqus: achjqz
disqus:

gitalk:
    on: false
    clientID: 
    clientSecret: 
    owner:
    admin:
    repo:       

# Analytics
# ga: UA-xxxxxxxx-x

# mermaid chart
mermaid: ## mermaid url https://github.com/knsv/mermaid
  enable: true  # default true
  version: "10.3.1" # default v7.1.2
  options:  # find more api options from https://github.com/knsv/mermaid/blob/master/src/mermaidAPI.js
    #startOnload: true  // default true

# Copyright Infomation
startyear: 2021